# Generated by Django 5.0.3 on 2024-04-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20)),
                ('license_plate_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('contact_method', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('sms', 'SMS')], max_length=10)),
            ],
        ),
    ]
